### ISSUE TITLE
evaluation problem

### ISSUE THREAD

**Issue by Zzoay** [chenshaowei57/SDRN#4]
Hi, thanks for the open source code. I have downloaded this code and its dataset and requirements. While I try to run main.py, the training loss and target_acc look ok, but the evaluation always works like this:
```
test: time: 4.95s, speed: 0.00st/s
relation result: Precision: 0.0000; Recall: 0.0000; F1: 0.0000
target result: Precision: 0.0000; Recall: 0.0000; F1: 0.0000
opinion result: Precision: 0.0000; Recall: 0.0000; F1: 0.0000
```
in each epoch, and also in mode "test".
Besides, the "relation_acc" is often 0.00 or a very small number when the model training.

**Comment by chenshaowei57** [comment]
我之前没有遇到过这个问题，你可以再检查一下环境是否正确，是不是正确加载了bert等

**Comment by Zzoay** [comment]
> 我之前没有遇到过这个问题，你可以再检查一下环境是否正确，是不是正确加载了bert等

问题确实是由BERT的产生的，BERT在训练阶段可以正常encode，而在测试阶段则会出现错误，但我暂时没有找到具体的原因，有可能是pytorch版本的原因（我的版本为1.7.0，由于我的cuda版本为10.2，似乎无法正常使用torch==0.4.0）(ㄒoㄒ)。
现将BERT模型交由transformers库来读取（用的是相同的模型文件和配置），解决了这个问题：
```
# in opinionMining.py
from transformers import BertModel
# line 29
# encoder
self.bert = BertModel.from_pretrained('bert-base-uncased')  # the bert model path, including pytorch.bin and config.json
# line 125 
# bert
all_outputs = self.bert(all_input_ids, all_segment_ids, all_input_mask)
sequence_output = all_outputs.last_hidden_state
```
无论如何，问题解决了，我觉得可以close这个issue了，十分感谢~

**Comment by Coldog2333** [comment]
@Zzoay 您好，想问一下您用的transformers版本是多少呀？

**Comment by Zzoay** [comment]
> @Zzoay 您好，想问一下您用的transformers版本是多少呀？

@Coldog2333 4.0.1

**Comment by liziming5353** [comment]
请问last_hidden_state是在哪里定义的呢
