### ISSUE TITLE
验证集

### ISSUE THREAD

**Issue by aopolin-lv** [chenshaowei57/SDRN#6]
您好：

我最近刚刚接触ABSA这个task，想follow您的工作，不过有一些细节问题想咨询一下您：
我看到在您的源码中，eval_dataset使用的是test数据集，这和我之前做过的其他任务不太一样，是因为train样本数量太少的原因，还是因为ABSA任务上其他工作都采用这种方式？

十分感谢！

**Comment by chenshaowei57** [comment]
您好，我当时follow了Coupled Multi-Layer Attentions for Co-Extraction of Aspect and Opinion Terms对数据集的划分和标注，所以就只包含了train和test。他们的代码中也只用test进行了测试。
